import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/session";
import prisma from "@/lib/prisma";

/**
 * GET /api/admin/promo-stats
 * Récupère les statistiques des codes promo
 */
export async function GET(request: NextRequest) {
  try {
    const session = await getSession();

    // Vérifier que l'utilisateur est admin
    if (!session.isLoggedIn || !session.user?.email) {
      return NextResponse.json(
        { error: "Non autorisé" },
        { status: 401 }
      );
    }

    const adminUser = await prisma.user.findUnique({
      where: { email: session.user.email },
    });

    if (!adminUser || adminUser.role !== "admin") {
      return NextResponse.json(
        { error: "Accès admin requis" },
        { status: 403 }
      );
    }

    // Récupérer tous les codes promo
    const allPromoCodes = await prisma.promoCode.findMany({
      include: {
        redemptions: true,
      },
    });

    // Statistiques globales
    const totalCodes = allPromoCodes.length;
    const autoGeneratedCodes = allPromoCodes.filter(c => c.createdBy === 'system_auto_promo').length;
    const manualCodes = allPromoCodes.filter(c => c.createdBy !== 'system_auto_promo').length;
    const activeCodes = allPromoCodes.filter(c => c.isActive).length;
    const expiredCodes = allPromoCodes.filter(c => new Date() > new Date(c.expiresAt)).length;

    // Codes utilisés
    const totalRedemptions = allPromoCodes.reduce((sum, code) => sum + code.currentUses, 0);
    const usedCodes = allPromoCodes.filter(c => c.currentUses > 0).length;
    const unusedCodes = allPromoCodes.filter(c => c.currentUses === 0).length;

    // Taux de conversion
    const conversionRate = totalCodes > 0 ? ((usedCodes / totalCodes) * 100).toFixed(1) : '0';

    // Répartition par période de facturation
    const monthlyOnlyCodes = allPromoCodes.filter(c => c.allowedBillingPeriod === 'MONTHLY').length;
    const yearlyOnlyCodes = allPromoCodes.filter(c => c.allowedBillingPeriod === 'YEARLY').length;
    const allPeriodsCodes = allPromoCodes.filter(c => c.allowedBillingPeriod === 'ALL').length;

    // Codes récents (derniers 10)
    const recentCodes = allPromoCodes
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, 10)
      .map(code => ({
        id: code.id,
        code: code.code,
        discountPercent: code.discountPercent,
        maxUses: code.maxUses,
        currentUses: code.currentUses,
        isActive: code.isActive,
        expiresAt: code.expiresAt,
        createdAt: code.createdAt,
        createdBy: code.createdBy,
        allowedBillingPeriod: code.allowedBillingPeriod,
        isExpired: new Date() > new Date(code.expiresAt),
        redemptions: code.redemptions.map(r => ({
          userEmail: r.userEmail,
          planId: r.planId,
          billing: r.billing,
          redeemedAt: r.redeemedAt,
        })),
      }));

    // Top codes par utilisation
    const topCodes = allPromoCodes
      .filter(c => c.currentUses > 0)
      .sort((a, b) => b.currentUses - a.currentUses)
      .slice(0, 5)
      .map(code => ({
        code: code.code,
        currentUses: code.currentUses,
        maxUses: code.maxUses,
        discountPercent: code.discountPercent,
      }));

    // Codes expirés récemment (derniers 7 jours)
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    const recentlyExpiredCodes = allPromoCodes
      .filter(c => {
        const expiry = new Date(c.expiresAt);
        return expiry < new Date() && expiry > sevenDaysAgo;
      })
      .length;

    // Codes qui expirent bientôt (prochains 7 jours)
    const sevenDaysLater = new Date();
    sevenDaysLater.setDate(sevenDaysLater.getDate() + 7);

    const expiringCodes = allPromoCodes
      .filter(c => {
        const expiry = new Date(c.expiresAt);
        return expiry > new Date() && expiry < sevenDaysLater && c.isActive;
      })
      .map(c => ({
        code: c.code,
        expiresAt: c.expiresAt,
        currentUses: c.currentUses,
        maxUses: c.maxUses,
      }));

    // Statistiques par jour (derniers 30 jours)
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const codesCreatedLast30Days = allPromoCodes.filter(c =>
      new Date(c.createdAt) > thirtyDaysAgo
    ).length;

    const redemptionsLast30Days = await prisma.promoCodeRedemption.count({
      where: {
        redeemedAt: {
          gte: thirtyDaysAgo,
        },
      },
    });

    return NextResponse.json({
      success: true,
      stats: {
        overview: {
          totalCodes,
          autoGeneratedCodes,
          manualCodes,
          activeCodes,
          expiredCodes,
          totalRedemptions,
          usedCodes,
          unusedCodes,
          conversionRate: parseFloat(conversionRate),
        },
        billingPeriods: {
          monthlyOnly: monthlyOnlyCodes,
          yearlyOnly: yearlyOnlyCodes,
          allPeriods: allPeriodsCodes,
        },
        recent: {
          codesCreated: recentCodes,
          recentlyExpired: recentlyExpiredCodes,
          expiringCodes,
          codesCreatedLast30Days,
          redemptionsLast30Days,
        },
        top: {
          mostUsedCodes: topCodes,
        },
      },
    });
  } catch (error: any) {
    console.error("❌ [Admin] Erreur lors de la récupération des stats:", error);
    return NextResponse.json(
      { error: "Erreur serveur", details: error.message },
      { status: 500 }
    );
  }
}
